### ISSUE TITLE
I want to know the format of input.

### ISSUE THREAD

**Issue by daichi-3110** [VisualComputingInstitute/dcm-net#4]
Hello. 

I want to know the format of input.
Is it (BatchSize, NumOfPoints, 9)? (9 is xyzrgb + normal(xyz))

Thank you.

**Comment by JonasSchult** [comment]
Hi Daichi,

Thanks for you interest in our code!

Unfortunately our input format is more complex than that of PointNet.
As we compute the mesh levels beforehand, we have to provide them as inputs to our network.
That is, we provide Euclidean and geodesic edges in each level, as well as the pooling trace maps interconnecting these levels.
Our initial nodes in the first level consists of XYZ coordinates, RGB color values and normal information. 
As each batch consists of 4 graphs of arbitrary size, we cannot use an additional batch dimension. To ensure that edge sets and pooling trace maps refer to the right nodes we find unique ids for each node in the batch. Please checkout https://github.com/JonasSchult/pytorch_geometric_fork/blob/master/torch_geometric/data/batch.py#L150 if you want to know more about this.

Please let me know if I can help you with more explanation.

Best,
Jonas

**Comment by JonasSchult** [comment]
As this issue seems unactive/solved to me, I will close it now.
Feel free to reopen it when you got further questions.

Best,
Jonas
