### ISSUE TITLE
Fail to compile Mesh Simplification Preprocessing (VCGlib)

### ISSUE THREAD

**Issue by HeCraneChen** [VisualComputingInstitute/dcm-net#5]
Hi Jonas,

Thank you for the amazing work and the code!

I followed the installation step by step, everything went good, until when I ran the "make" for QUADRIC ERROR METRICS. I got the errors below. Seems like something wrong in the cpp file. Could you please have a look at that? 

And to clearify, by "Add vcglib/apps/tridecimator and vcglib/apps/sample/trimesh_clustering to your environment path variable!", is this the right thing to do or not?

PATH=$PATH:vcglib/apps/tridecimator
PATH=$PATH:vcglib/apps/sample/trimesh_clustering

Appreciate your attention!

tridecimator.cpp: In function ‘int main(int, char**)’:
tridecimator.cpp:165:147: error: ‘dup_face’ was not declared in this scope
 face %i and edge %i and deg vertex %i and deg face %i\n",dup,unref, dup_face, dup_edge, deg_vertex, deg_face);
                                                                     ^~~~~~~~
tridecimator.cpp:165:157: error: ‘dup_edge’ was not declared in this scope
 d edge %i and deg vertex %i and deg face %i\n",dup,unref, dup_face, dup_edge, deg_vertex, deg_face);
                                                                     ^~~~~~~~
tridecimator.cpp:165:167: error: ‘deg_vertex’ was not declared in this scope
 and deg vertex %i and deg face %i\n",dup,unref, dup_face, dup_edge, deg_vertex, deg_face);
                                                                     ^~~~~~~~~~
tridecimator.cpp:165:179: error: ‘deg_face’ was not declared in this scope
 tex %i and deg face %i\n",dup,unref, dup_face, dup_edge, deg_vertex, deg_face);
                                                                      ^~~~~~~~
tridecimator.cpp:171:32: error: ‘FinalSize’ was not declared in this scope
   printf("reducing it to %i\n",FinalSize);
                                ^~~~~~~~~

**Comment by JonasSchult** [comment]
Hi HeCraneChen,

thank you a lot for your interest in our codebase.

Regarding adding the directories to the path variable:
In my .bashrc it looks as following:
```
export PATH=/home/user_name/vcglib/apps/tridecimator/:$PATH
export PATH=/home/user_name/vcglib/apps/sample/trimesh_clustering/:$PATH
```
I will look into the compilation error next week and come back to you as soon as possible.

**Comment by JonasSchult** [comment]
Hi HeCraneChen,

I just checked the code of vcglib. As it turned out, I accidentally didn't push the latest version of the code to the public repository.
The issue should be fixed now. Hope the code will help you!

Best,
Jonas

**Comment by JonasSchult** [comment]
As this issue seems unactive/solved to me, I will close it now.
Feel free to reopen it when you got further questions.

Best,
Jonas
