### ISSUE TITLE
vcglib - undeclared variables in apps/tridecimator

### ISSUE THREAD

**Issue by lppllppl920** [VisualComputingInstitute/dcm-net#6]
Hi,

Thank you so much for creating this great work. I have one question regarding the vcglib that you shared. It seems to me that there are some undeclared variables in tridecimator.cpp. Would you mind fixing this issue for us?

Best,
Xingtong

**Comment by JonasSchult** [comment]
Hi Xingtong,

thanks for your interest in our code and pointing out that problem!
I will look into that matter next week and get back to you as soon as possible.
Updates will be posted under the issue #5 . 

Best regards
Jonas
