### ISSUE TITLE
Visualization software

### ISSUE THREAD

**Issue by wusuoweima** [VisualComputingInstitute/dcm-net#9]
I am more interested in your visualization in Figure 1. Could you share the visualization software you use? 
@JonasSchult

**Comment by JonasSchult** [comment]
Hi wusuoweima,

thank you for your interest in our project!

You can use `example_scripts/visualize_scannet.sh` to get a preliminary (not globally illuminated) rendering of the scene, with which you can interactively work. By pressing `d`, the visualization tool outputs a `.ply` file which you can then import into the 3D graphics suite of your choice. We used Blender for the globally illuminated renderings of our paper.
More information about the visualizer is given in the readme file.

Best,
Jonas
